### ISSUE TITLE
APKs corrupt

### ISSUE THREAD

**Issue by tinker1234** [necrodraco/YGOPRO_Android#1]
I've tried them all they seem to be corrupted

**Comment by necrodraco** [comment]
I installed the animeExperimental from 01-01-2019  and the app installs, starts and the deck edit work. 
So which element should be corrupted?

**Comment by grimoiregianflo** [comment]
Hi the apk and the zip parts still result corrupted and only the experimental apk installs. Already tryed to install or download it in other devices to see if it was my tablet's fault, but it's always the same. Any help?

**Comment by necrodraco** [comment]
Hi @grimoiregianflo , 
I found the failure of the non-experimental APKs. they should be fixed now. But the zip-parts aren't corrupted. You need to download all of them and place them in the same folder, before you unzip them. 

And due to the missing answer of @tinker1234 I will close this issue now
